# Generated by Django 4.1.3 on 2022-11-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_category_cuisine_menu_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='menu_items.category'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='cuisine',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='menu_items.cuisine'),
        ),
    ]
