# Generated by Django 4.1.3 on 2022-11-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0003_alter_menu_item_category_alter_menu_item_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_items.category'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='cuisine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_items.cuisine'),
        ),
    ]
