# Generated by Django 4.1.3 on 2022-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0004_alter_menu_item_category_alter_menu_item_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='description',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
