# Generated by Django 4.1.3 on 2022-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0005_menu_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
