# Generated by Django 4.1.3 on 2022-11-10 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0006_menu_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='spice_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=5),
        ),
    ]
