# Generated by Django 4.1.3 on 2022-11-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='menu_items',
            field=models.ManyToManyField(to='menu_items.menu_item'),
        ),
    ]
